malloc: Use UINTN instead of EFI_PHYSICAL_ADDRESS for casts
EFI_PHYSICAL_ADDRESS is a 64-bit data type, which when used to cast to
a 32-bit pointer leads to the following warnings,

cc1: warnings being treated as errors
malloc.c: In function ‘emalloc’:
malloc.c:60:6: error: cast from pointer to integer of different size
malloc.c:61:12: error: cast from pointer to integer of different size
malloc.c:67:10: error: cast to pointer from integer of different size

UINTN is a much more logical choice for this cast because it maps to
unsigned long, which will Do The Right Thing for both i386 and x86-64.

Signed-off-by: Matt Fleming <matt.fleming@intel.com>