protocol.h: Remove unused locate_protocol()
locate_protocol() has never been used by efilinux and results in the
following build error when compiled with gnu-efi <= 3.0i,

In file included from entry.c:38:0:
protocol.h: In function 'locate_protocol':
protocol.h:62:31: error: 'EFI_BOOT_SERVICES' has no member named 'LocateProtocol'

Reported-by: KESHAV P.R. <skodabenz@gmail.com>
Reported-by: Metatech <metatechbe@gmail.com>
Signed-off-by: Matt Fleming <matt.fleming@intel.com>