bzimage: Only set efi_*_hi for x86-64
It doesn't make sense to set efi_systab_hi or efi_memmap_hi for i386
because the 32-bit addresses fit in efi_systab and efi_memmap. Also,
shifting the systab and memmap pointers results in the following
warnings,

loaders/bzimage/bzimage.c:324:2: error: right shift count >= width of type
loaders/bzimage/bzimage.c:325:2: error: right shift count >= width of type

Signed-off-by: Matt Fleming <matt.fleming@intel.com>